export const CONTACT_REQUEST = "CONTACT_REQUEST"
export const CONTACT_SUCCESS = "CONTACT_SUCCESS"
export const CONTACT_FAIL = "CONTACT_FAIL"

export const CONTACT_TAMBAH_REQUEST = "CONTACT_TAMBAH_REQUEST"
export const CONTACT_TAMBAH_SUCCESS = "CONTACT_TAMBAH_SUCCESS"
export const CONTACT_TAMBAH_FAIL = "CONTACT_TAMBAH_FAIL"

export const CONTACT_UPDATE_REQUEST = "CONTACT_UPDATE_REQUEST"
export const CONTACT_UPDATE_SUCCESS = "CONTACT_UPDATE_SUCCESS"
export const CONTACT_UPDATE_FAIL = "CONTACT_UPDATE_FAIL"

export const CONTACT_DELETE_REQUEST = "CONTACT_DELETE_REQUEST"
export const CONTACT_DELETE_SUCCESS = "CONTACT_DELETE_SUCCESS"
export const CONTACT_DELETE_FAIL = "CONTACT_DELETE_FAIL"
